apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django       # must match the label on your pod
  ports:
    - protocol: TCP
      port: 8000      # external port for minikube
      targetPort: 8000
  type: NodePort
